enum WiFiAuthModeEnum {
    WIFI_AUTH_OPEN = 0,
    WIFI_AUTH_WEP = 1,
    WIFI_AUTH_WPA_PSK = 2,
    WIFI_AUTH_WPA2_PSK = 3,
    WIFI_AUTH_WPA_WPA2_PSK = 4,
    WIFI_AUTH_ENTERPRISE = 5,
    WIFI_AUTH_WPA3_PSK = 6,
    WIFI_AUTH_WPA2_WPA3_PSK = 7,
    WIFI_AUTH_WPA3_ENT_192 = 10,
    WIFI_AUTH_WPA3_ENTERPRISE = 14,
    WIFI_AUTH_WPA2_WPA3_ENTERPRISE = 15,
    WIFI_AUTH_OWE = 9
}

export enum WiFiAuthModeNameEnum {
    WIFI_AUTH_OPEN = "Open",
    WIFI_AUTH_WEP = "WEP",
    WIFI_AUTH_WPA_PSK = "WPA-PSK",
    WIFI_AUTH_WPA2_PSK = "WPA2-PSK",
    WIFI_AUTH_WPA_WPA2_PSK = "WPA/WPA2-PSK",
    WIFI_AUTH_ENTERPRISE = "Enterprise",
    WIFI_AUTH_WPA3_PSK = "WPA3-PSK",
    WIFI_AUTH_WPA2_WPA3_PSK = "WPA2/WPA3-PSK",
    WIFI_AUTH_WPA3_ENT_192 = "WPA3-Enterprise-192",
    WIFI_AUTH_WPA3_ENTERPRISE = "WPA3-Enterprise",
    WIFI_AUTH_WPA2_WPA3_ENTERPRISE = "WPA2/WPA3-Enterprise",
    WIFI_AUTH_OWE = "OWE"
}

export default WiFiAuthModeEnum;